source 'https://rubygems.org'

gem 'cellar', '~> 0.0.8'

# # please, uncoment gems that you want to use
# gem 'coffee-script'
# gem 'sass'
# gem 'less'
# gem 'therubyracer' # dependent for Less

gem 'thin'

